# Generated by Django 4.2.5 on 2023-10-26 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monday', models.CharField(default='10:30 am - 6:30 pm', max_length=100)),
                ('tuesday', models.CharField(default='10:30 am - 6:30 pm', max_length=100)),
                ('wednesday', models.CharField(default='10:30 am - 6:30 pm', max_length=100)),
                ('thursday', models.CharField(default='10:30 am - 6:30 pm', max_length=100)),
                ('friday', models.CharField(default='10:30 am - 6:30 pm', max_length=100)),
                ('saturday', models.CharField(default='10:30 am - 6:30 pm', max_length=100)),
                ('sunday', models.CharField(default='Closed', max_length=100)),
                ('date_updated', models.DateField(default=django.utils.timezone.now)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(default='Claire', max_length=100)),
                ('img', models.TextField(default='https://lh3.googleusercontent.com/a/ACg8ocJXZofFupD7SwebKyeqFM7evCP_HUPW0Hkfn-YPVUIl=w68-h68-p-rp-mo-br100')),
                ('text', models.TextField(default='The Best Shop on the block!')),
                ('link', models.TextField(default='https://lh3.googleusercontent.com/a/ACg8ocJXZofFupD7SwebKyeqFM7evCP_HUPW0Hkfn-YPVUIl=w68-h68-p-rp-mo-br100')),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
