# Generated by Django 4.2.5 on 2023-10-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('subscribed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Email List',
            },
        ),
        migrations.AlterModelOptions(
            name='hours',
            options={'verbose_name_plural': 'Hours'},
        ),
    ]
