# Generated by Django 4.2.5 on 2023-10-26 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_emaillist_alter_hours_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Promo', max_length=100)),
                ('description', models.TextField(blank=True, default='A New Promo')),
                ('photo', models.ImageField(default='transplogo.png', upload_to='images/promos/')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('EX', 'Expired'), ('CS', 'Coming Soon'), ('OT', 'Other')], default='AC', max_length=2)),
                ('visible', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
            ],
        ),
    ]
