# Generated by Django 4.2.5 on 2023-10-27 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Eyecare', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='A New Article', max_length=250)),
                ('author', models.CharField(blank=True, default='Eyes of Jamaica', max_length=250)),
                ('description', models.TextField(blank=True, default='A New article')),
                ('photo', models.ImageField(default='default_article.jpg', upload_to='images/library/')),
                ('text', models.TextField(default='Article Text')),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(default=django.utils.timezone.now)),
                ('visible', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, to='index.tag')),
            ],
        ),
    ]
