# Generated by Django 5.0.1 on 2024-03-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_tag_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='description',
            new_name='en_description',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='name',
            new_name='en_name',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='photo',
            new_name='en_photo',
        ),
    ]
