# Generated by Django 5.0.1 on 2024-03-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_rename_description_promotion_en_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='es_description',
            field=models.TextField(blank=True, default='SPANISH A New Promo description'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='es_name',
            field=models.CharField(default='SPANISH New Promo', max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='es_photo',
            field=models.ImageField(default='transplogo.png', upload_to='images/promos/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='en_description',
            field=models.TextField(blank=True, default='A New Promo description'),
        ),
    ]
