# Generated by Django 5.0.1 on 2024-03-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_promotion_es_description_promotion_es_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_description', models.TextField(blank=True, default='A New Promo description')),
                ('es_description', models.TextField(blank=True, default='SPANISH A New Promo description')),
                ('en_photo', models.ImageField(default='transplogo.png', upload_to='images/Photos/')),
                ('es_photo', models.ImageField(default='transplogo.png', upload_to='images/Photos/')),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
    ]
