# Generated by Django 5.0.1 on 2024-03-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='en_text',
        ),
        migrations.AddField(
            model_name='review',
            name='es_text',
            field=models.TextField(default='The Best Shop on the block!'),
        ),
    ]
