# Generated by Django 5.0.1 on 2024-03-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_rename_article_old_article_rename_tag_old_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='old_Article',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='old_Tag',
            new_name='Tag',
        ),
    ]
