# Generated by Django 5.0.1 on 2024-03-26 17:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_rename_old_article_article_rename_old_tag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='en_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='DEFAULT TEXT'),
        ),
        migrations.AddField(
            model_name='article',
            name='es_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='DEFAULT TEXT'),
        ),
        migrations.AddField(
            model_name='article',
            name='es_description',
            field=models.TextField(blank=True, default='A New article'),
        ),
        migrations.AddField(
            model_name='article',
            name='es_title',
            field=models.CharField(default='A New Article', max_length=250),
        ),
        migrations.AddField(
            model_name='tag',
            name='es_name',
            field=models.CharField(default='Eyecare', max_length=64),
        ),
    ]
