# Generated by Django 5.0.1 on 2024-03-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_article_en_body_article_es_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='en_title',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='en_name',
        ),
    ]
